[build]
  command = "pnpm build"
  publish = "dist/pwa"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Content-Type = "application/javascript"
    Service-Worker-Allowed = "/"
